---
- hosts: all
  gather_facts: false

  tasks:
  - name: Create a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "lab.akmf"
      folder: "lab.akmf/ansible"
      name: "lab-ansible"
      state: present
      snapshot_name: ansible_snapshot
      description: ansible_snapshot
    delegate_to: localhost